### PR TITLE
ENYO-1012: Added ha-Latn-NG to the use-non-latin-fonts list

### PR DESCRIPTION
**Pull request by Djspaceg**
Misc trailing whitespace cleanup. Actual change on line [L#266](https://github.com/enyojs/enyo-ilib/compare/ENYO-1012-blakestephens?expand=1#diff-a5d7aa73ff570d486fbe431016d50de0R266)

Enyo-DCO-1.1-Signed-off-by: Blake Stephens <blake.stephens@lge.com>

### CODE REVIEW

**Comment by ehoogerbeets** [comment]
Hey Blake, ENYO-1012 seems to be unrelated to this. Is that the right bug?

Also, Hausa is going to have its own font. Does it need to be in the non-latin case?

**Comment by Djspaceg** [comment]
@ehoogerbeets This adds Hausa (ha-Latn-NG, specifically the "ha" part) to the list of latin-languages which are treated as if they are non-latin languages. These targeted languages are assigned to the non-latin font. If we add a special Hausa font, we can add that additional rule later, when the font is identified.

This PR addresses bullet #3 and paragraph 2 from the description in ENYO-1012.

Let me know if/when the new font is added and ready.

**Comment by ehoogerbeets** [comment]
Is this the right issue? https://enyojs.atlassian.net/browse/ENYO-1012 
It talks about adding an animated property to onyx.Drawer...

**Comment by Djspaceg** [comment]
Nope. ENYO-1012 on the internal Jira. ;)

**Pull request merged**
