### PR TITLE
Update to ilib build 20150814-build-11.0-005-02

### PR DESCRIPTION
**Pull request by gouniLee**
Update to ilib build 20150729-build-11.0-005-01. The ilib-webapp  part  is already submitted  to the Build. (master, drd4tv)

* Fixed missing dependency in Currency.js
* Fixed some closure compiler warnings
* Calendar.newDateInstance() is now deprecated, as it creates a circular dependency. This call will go away in release 13.0 or 14.0. The alternate way of creating a date for a particular calendar is to call the date factory directly instead of having the calendar classes do it for you:
```
Before:
var d = cal.newDateInstance();
After:
var d = DateFactory({calendar: cal.getType()});
Souped up the jsdocs a bit
```
* Fixed bug where creating a new ResBundle would throw an exception if there were no arguments to the constructor AND the current locale was a pseudo locale.

### CODE REVIEW

**Comment by kyo504** [comment]
@aarontam @gouniLee - Could you check this? Current version of onDevice-ilib is *11.0.005* so we need to sync both of ilib.

**Comment by aarontam** [comment]
@kyo504 Is this needed for pre.15.1?

**Comment by kyo504** [comment]
If container uses onDevice ilib, we don't have to but if not, this needs to be merged pre.15.1

**Comment by graynorton** [comment]
@JayCanuck, are we currently using the on-device iLib in the build (see @kyo504's note above)?

**Comment by JayCanuck** [comment]
We are currently using on-device ilib with container, yes.

**Comment by webOS101** [comment]
This has a circular dependency. This was fixed with https://github.com/enyojs/iLib/pull/34.  Please rebase to that commit.

**Comment by gouniLee** [comment]
I've added https://github.com/enyojs/iLib/pull/34 patch. 
fyi, ilib-webapp for webOS TV, it's already applied with version "build 20150814-build-11.0-005-02" and merged to drd4tv_60.

**Comment by JayCanuck** [comment]
We the fix for circular dependency added, we can probably remove enyo-ilib/lib/patch.js eh? @ryanjduffy

**Comment by ryanjduffy** [comment]
Ya. Let's open a separate ticket for that and we can revert that commit 328bce3d1c76348f93cc45ebefc63a5a71095bb7

**Pull request merged**
