### PR TITLE
ENYO-2359: Add missing module require.

### PR DESCRIPTION
**Pull request by aarontam**
### Issue
The `ResBundle` module is being used by `Currency`, but it is not required.

### Fix
We require the `ResBundle` module.

### Notes
This was discovered in the course of creating https://github.com/enyojs/enyo-strawman/pull/116.

Enyo-DCO-1.1-Signed-off-by: Aaron Tam <aaron.tam@lge.com>

### CODE REVIEW

**Comment by webOS101** [comment]
why does this file show up as a single line? :(

**Comment by aarontam** [comment]
The file format was already like that, as were the other modules - I was going to ask @ryanjduffy about that, but threw the PR out there for the time being.

**Comment by ehoogerbeets** [comment]
Few problems/notes:

- the reason it is all on one line is that it is not a source file. Instead, it is the result of the ilib uglify build, so if you modify this file, your change will be overwritten in the next ilib build.
- the results of the ilib build comes from the enyojs/ilib which is the master of the LG-updated sources. (ie. it is open-source ilib + LG-specific overrides, especially for the locale data)
- @everyevery put in an automatic system that sucks in the open-source ilib sources into a branch of this project, and then merges it on top of the LG mods. Then, a build is performed and the results are checked in to enyo-ilib.
- Much better would be to ask me to put this modification into the original ilib open source and have it eventually be automatically sucked in here. You have just hereby done this. ;-) I will update the trunk of ilib shortly. This should probably be closed unmerged.

**Comment by ehoogerbeets** [comment]
Actually, now that I check it, it looks like @gouniLee already made that fix. I guess what is needed now is an ilib build in order to fix that.

**Comment by aarontam** [comment]
Excellent, we can close this out then.

**Pull request closed without merging**
