### PR TITLE
Update to build 20150331-build-10.0-005

### PR DESCRIPTION
**Pull request by gouniLee**
This pull request should be merged after https://github.com/enyojs/enyo-ilib/pull/117 in master. I created branch from 'release-2.5.3-pre.16.w'
The ilib-webapp part is already submitted to the TV build.  A "am-ET" is new locale for MR. and new ethiopic calendar feature is include this pull request.  so I hope it could be merged next enyo release to sync with ilib-webapp part.

- Added unit test cases to verify support for the following languages: af (Afrikaans), am (Amharic), ha (Hausa), or (Oriya)
- Added support for the Ethiopic and Coptic calendars including the calendar date objects, date formatting, date range formatting, and duration formatting
- Added getStringJS() convenience method to ilib.ResBundle. This returns a Javascript string object instead of the ilib.String that getString() returns.
- Fixed day names in Vietnamese long format from the 3-letter abbreviations of the full names to "CN" (Sunday) followed by "Th 1" (Monday) through "Th 7" (Saturday).
- Now uses the 64-bit getTimeExtended() instead of old 32-bit getTime() where possible. The ilib.Date object uses the built-in Javascript Date object to calculate the offset of the "local" time zone, which is faster than the pure JS algorithm and is always in sync with the system time zone db. Using getTimeExtended() effectively widens the time period when the "local" time zone can use the built-in Date for these calculations.
- Updated the country name translations for af, am, ha, or, and pa. These are used in address parsing and formatting.
- Changed am and pm symbols in Gujarati to "AM" and "PM" to match CLDR.
- Fixed unit formatting in Chinese. Removed some bogus directories under js/data/locale/zh and moved the unitfmt.json files in the bogus dirs to the correct places instead so the code can pick them up.

### CODE REVIEW

**Comment by gouniLee** [comment]
hi @aarontam, this is the enyo-ilib part of the submissions. The ilib-webapp part is already submitted to the TV build.

**Comment by aarontam** [comment]
Hi @gouniLee, we'll merge this in once we're done with our modularization work, thanks.

cc @clinuz

**Comment by graynorton** [comment]
@gouniLee @ericseong @lishammel @aarontam @clinuz

I think we need to take these changes for 2.5 as well -- @ericseong, please confirm.

If so, we'll need a separate pull request for that. @gouniLee, can you prepare one? @aarontam, can you advise / assist as needed?

**Comment by clinuz** [comment]
These changes should immediately be applicable to 2.5.x right? The 2.6+ adoption will have to be done manually later as stated above. @gouniLee will these changes already be included in the upcoming release of ilib? If so, then we will  be able to skip taking this for 2.6 at all and it will come along automatically when we update to that future release.

**Comment by ehoogerbeets** [comment]
Yes, this ilib build should be used with enyo 2.5.x. The changes in this build will be in the modularized code as well, as the modularization branch is based on this build. So yes, this can be skipped for 2.6 for now.

**Comment by gouniLee** [comment]
Based on the comments before, It looks like that I have to prepare pull request for 2.5.x.  @aarontam Could you  tell me which branch that I have to submit PR?

**Comment by aarontam** [comment]
Hi @gouniLee, the PR should be made against the `2.5-upkeep` branch for the 2.5.4-pre.x releases, thanks!

**Comment by gouniLee** [comment]
Hi @aarontam I did  PR for 2.5-upkeep branch in order to apply latest version of iLib. Please see the https://github.com/enyojs/enyo-ilib/pull/119. Thank you

**Comment by gouniLee** [comment]
It's not correct pull request. I supposed to dd to release-2.5.3-pre.16.w. but I did it to master. Sorry about that. I think It's better to close this PR.

**Pull request closed without merging**
