### PR TITLE
Added check for navigator.language for ie 10 support

### PR DESCRIPTION
**Pull request by rundmt**
Also removed whitespaces from file.

Enyo-DCO-1.1-Signed-off-by: Derek Tor derek.tor@lge.com

### CODE REVIEW

**Comment by ehoogerbeetsLingoport** [comment]
enyo-ilib contains a mirror of the open-source ilib project on sourceforge. Changes should not be made here to the base ilib code. Please submit the change on sourceforge instead. See https://sourceforge.net/projects/i18nlib/

**Comment by ehoogerbeetsLingoport** [comment]
Actually, please contact Goun Lee (goun.lee@lge.com) if you would like to have the international team do that for you.

**Comment by rundmt** [comment]
Closing as fixes need to be made in ilib.

**Comment by rundmt** [comment]
Reopening because there are no plans to build a new enyo-ilib in 2.7 timeframe.

**Pull request closed without merging**
