### PR TITLE
Update to build 20150213-build-10.0-002

### PR DESCRIPTION
**Pull request by ehoogerbeets**
* Completed support for address parsing in all current countries in the world. (This adds support for CL, DO, ET, HU, IN, IS, KG, KW, LU, MO, NI, NO, PA, PE, PY, RS, RU, SA, SL, SN)
* Add support to ilib.LocaleInfo to return the start and end of the weekend for the locale. This returns days-of-the-week numbers (ie. Sunday=0, Monday=1, etc.)
* The number of fraction digits supported by the ilib.NumFmt class is now limited from 0 to 20 explicitly. Previously, it was quietly limited by the JS engine. Now, negative numbers go to 0, and numbers greater than 20 mean exactly 20.
* Fixed an exception in ilib.DateFmt when some formats could not be loaded from the locale data
* Fixed Korean name parsing to be able to handle spaces in the name
* Worked around a problem in Chrome 40 where the value of navigator.language no longer conforms to BCP-47. In the US for example, navigator.language now has "en-us" in it instead of "en-US" like it had in previous versions.

### CODE REVIEW

**Comment by ehoogerbeets** [comment]
Aaron, this is the enyo-ilib part of the submissions. The ilib-webapp part is not yet submitted to the TV build.

**Comment by gouniLee** [comment]
@aarontam Could you merge this PR? The ilib-webapp part is already applied with more the latest version as 20150316-build-10.0-004. and Applying ilib build 20150331-build-10.0-005 to ilib-webapp for TV is also in progress.

**Comment by aarontam** [comment]
Hi @gouniLee, yep no problem, I'll take care of the merge.

**Comment by gouniLee** [comment]
@aarontam Thank you!

**Comment by aarontam** [comment]
Closing in favor of https://github.com/enyojs/enyo-ilib/pull/117.

**Pull request closed without merging**
